### PR TITLE
reduce maximum points to 150 based on decreasing sampling

### PR DESCRIPTION
**Pull request by liufengyun**
reduce maximum points to 150 based on decreasing sampling

A fix to https://github.com/liufengyun/bench/issues/62

### CODE REVIEW

**Comment by liufengyun** [comment]
Review @smarter, thanks.

**Comment by smarter** [comment]
Could we have a checkbox or something to enable all points? It can still be useful sometimes.

**Comment by liufengyun** [comment]
Thanks @smarter , I'll try and see if it's easy to do.

**Comment by liufengyun** [comment]
@smarter It's now implemented with an option to show all points. I just deployed, it'll be live shortly.

**Pull request merged**
