### PR TITLE
Add max line

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by liufengyun** [comment]
I just ran it locally, it seems the max is not very informative, partly due to insufficient warmup, I guess.

screen shot 2017-07-27 at 10 35 56

**Comment by nicolasstucki** [comment]
Which would inform us that we are maybe missing some warmup

**Comment by nicolasstucki** [comment]
Tough this does not look that unexpected.

**Comment by nicolasstucki** [comment]
If at some point the max would jump to 3x the med, then  we would know that there is something wrong somewhere.

**Comment by nicolasstucki** [comment]
@DarkDimius WDYT?

**Pull request closed without merging**
